name: Deployment
on: [push]

jobs:
  Deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: docs_compiler
    
    steps:

      - name: Compile and build snippets
        run: node .

      - name: Push new snippets to repository
        run: |
          cd dist
          git commit -m "Update snippets"
          git push

      - name: Build and publish VSCode extension
        run: |
          cd dist/vscode
          vsce package
          vsce publish
